algo = str(input("Digite algo: "))
print(f"O tipo primitivo desse valor é {type(algo)}")
print(f"Só tem espaços? {algo.isspace()}")
print(f"É um numero? {algo.isalnum()}")
print(f"É alfabético? {algo.isalpha()}")
print(f"É alfanumérico? {algo.isnumeric()}")
print(f"Está em maiúsculas? {algo.isupper()}")
print(f"Está em minúsculas? {algo.islower()}")
print(f"Está capitalizada? {algo.title()}")